### ISSUE TITLE
Regression between 0.6.12 and 0.7.1: TODO

### ISSUE THREAD

**Issue by jpd236** [Kotlin/kotlinx.html#171]
I'm working on a Kotlin project which targets the browser (specifically for a Chrome extension). I have a simple snippet of code to append a link to an HTMLDivElement:

```kotlin
body.append {
    a {
        attributes["download"] = filename
        href = dataUrl
        +filename
    }
}
```

When my project depends on kotlinx-html-js 0.6.12, this works fine.

When I upgrade to 0.7.1 or newer, I get an error: `TypeError: visitTagAndFinalize is not a function`. The line of code in the generated Javascript that's failing is:

```kotlin
Kotlin.isType(tmp$ = visitTagAndFinalize(new A_init(attributesMapOf(['href', null, 'target', null, 'class', null]), $receiver), $receiver, visitAndFinalize$lambda(block)), HTMLAnchorElement_0) ? tmp$ : throwCCE();
```

visitTagAndFinalize is undefined, per the debugger. It's initialized here:

```kotlin
var visitTagAndFinalize = $module$kotlinx_html_js.kotlinx.html.visitTagAndFinalize_g9qte5$;
```

I see in the release notes that there's a change related to this function in 0.7.1 (see #130). Could this be related?

**Comment by jpd236** [comment]
Not seeing this issue in 0.7.3. I suspect it was fixed by https://github.com/Kotlin/kotlinx.html/commit/10c29c40e0f30c320fabb7a09bd798fc8b1cec4e but not sure.
